/**
 * Opaque avatar tokens and the `Profile.avatarUrl` contract.
 *
 * `Profile.avatarUrl` is server-owned. It is either `null` or a same-origin path
 * under `/avatars/`, and it can never become an arbitrary `https://` URL, a
 * `data:` URL, a raw storage URL, or anything a user typed. No client input
 * reaches this module: tokens are generated here from a cryptographic RNG, and
 * the only thing ever read back out of the database is re-parsed with the strict
 * parser below before it is used to build a storage key.
 */

/** The single route prefix that serves avatars. */
export const AVATAR_ROUTE_PREFIX = "/avatars/";

/** The fixed storage namespace. Never derived from a filename or a user field. */
export const AVATAR_STORAGE_PREFIX = "avatars/";

/** Stored avatars are always normalized WebP. */
export const AVATAR_CONTENT_TYPE = "image/webp";

const STORAGE_SUFFIX = ".webp";

/** Generated by `crypto.randomUUID`, so a fixed pattern is a valid expectation. */
const TOKEN_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** Whether a value is a well-formed opaque avatar token. */
export function isValidAvatarToken(value: string): boolean {
  return TOKEN_PATTERN.test(value);
}

/**
 * Generate a fresh opaque token.
 *
 * `crypto.randomUUID` is a CSPRNG-backed v4 UUID. It is deliberately unrelated to
 * the email address, display name, and user id, so a token discloses nothing about
 * its owner even if it leaks.
 */
export function generateAvatarToken(): string {
  return crypto.randomUUID();
}

/** The same-origin URL stored in `Profile.avatarUrl` for a token. */
export function avatarUrlForToken(token: string): string {
  if (!isValidAvatarToken(token)) {
    throw new Error("Refusing to build an avatar URL from an invalid token.");
  }

  return `${AVATAR_ROUTE_PREFIX}${token}`;
}

/** The storage object key for a token. Server-owned and namespace-fixed. */
export function avatarObjectKeyForToken(token: string): string {
  if (!isValidAvatarToken(token)) {
    throw new Error("Refusing to build a storage key from an invalid token.");
  }

  return `${AVATAR_STORAGE_PREFIX}${token}${STORAGE_SUFFIX}`;
}

/**
 * Recover the token from a stored `avatarUrl`, or `null` when the value is not
 * exactly the TeamMate-owned avatar route.
 *
 * Deliberately strict, and used before any storage deletion so an unexpected or
 * legacy value can never be translated into an arbitrary object key:
 *
 * - must be a relative path, so an absolute or protocol-relative URL is rejected;
 * - must be exactly the `/avatars/` prefix plus one bare token, so `..`, extra
 *   segments, a trailing slash, a query, or a fragment are all rejected;
 * - the token must match the generated shape exactly.
 */
export function parseAvatarTokenFromUrl(value: string | null): string | null {
  if (typeof value !== "string" || value.length === 0) {
    return null;
  }

  // Reject anything that is not a plain same-origin path before parsing.
  if (value.includes("://") || value.startsWith("//")) {
    return null;
  }

  if (!value.startsWith(AVATAR_ROUTE_PREFIX)) {
    return null;
  }

  const remainder = value.slice(AVATAR_ROUTE_PREFIX.length);

  // A query, fragment, or extra path segment means this is not our exact shape.
  if (
    remainder.includes("/") ||
    remainder.includes("?") ||
    remainder.includes("#")
  ) {
    return null;
  }

  return isValidAvatarToken(remainder) ? remainder : null;
}

/**
 * The storage key an existing `avatarUrl` refers to, or `null`.
 *
 * Returning `null` for anything unrecognized is what keeps a legacy or
 * externally-set value from ever becoming a deletion target.
 */
export function avatarObjectKeyFromUrl(value: string | null): string | null {
  const token = parseAvatarTokenFromUrl(value);
  return token === null ? null : avatarObjectKeyForToken(token);
}
